# Generated by Django 6.0.2 on 2026-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='latitud',
            new_name='latitud_real',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='longitud',
            new_name='longitud_real',
        ),
        migrations.RemoveField(
            model_name='perimetro',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='valido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perimetro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perimetro',
            name='radio_metros',
            field=models.IntegerField(default=50),
        ),
    ]
