# Generated by Django 6.0.2 on 2026-02-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_latitud_asistencia_latitud_real_and_more'),
        ('users', '0003_alter_horario_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='perimetro',
            options={'verbose_name': 'Perímetro', 'verbose_name_plural': 'Perímetros'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='distancia_metros',
            field=models.FloatField(default=0, help_text='Distancia al centro del perímetro en metros'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='perimetro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='locations.perimetro'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='users.usuario'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('retardo', 'Retardo'), ('justificacion', 'Justificación'), ('salida_temprana', 'Salida Temprana')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='users.usuario')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
