# Generated by Django 6.0.2 on 2026-02-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_asistencia_options_alter_perimetro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='bssid_conectado',
            field=models.CharField(blank=True, default='', help_text='BSSID del dispositivo al registrar', max_length=17),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ssid_conectado',
            field=models.CharField(blank=True, default='', help_text='SSID del dispositivo al registrar', max_length=100),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='wifi_valido',
            field=models.BooleanField(default=False, help_text='Si la red Wi-Fi coincide con una autorizada'),
        ),
        migrations.CreateModel(
            name='RedAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la red (ej: Sala de maestros)', max_length=100)),
                ('ssid', models.CharField(help_text='Nombre de la red Wi-Fi (SSID)', max_length=100)),
                ('bssid', models.CharField(help_text='MAC del punto de acceso (formato XX:XX:XX:XX:XX:XX)', max_length=17)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Ubicación o detalles del access point')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Red Autorizada',
                'verbose_name_plural': 'Redes Autorizadas',
                'unique_together': {('ssid', 'bssid')},
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='red_autorizada',
            field=models.ForeignKey(blank=True, help_text='Red Wi-Fi usada al registrar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='locations.redautorizada'),
        ),
    ]
