# Generated by Django 6.0.2 on 2026-03-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_incidencia_asistencia_fk_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('falta', 'Falta'), ('retardo', 'Retardo'), ('justificacion', 'Justificación'), ('salida_temprana', 'Salida Temprana'), ('olvido_salida', 'Olvidó marcar salida')], max_length=20),
        ),
    ]
