# Generated by Django 6.0.2 on 2026-03-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_asistencia_bssid_conectado_asistencia_ssid_conectado_and_more'),
        ('users', '0003_alter_horario_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='asistencia',
            field=models.ForeignKey(blank=True, help_text='Registro de asistencia que originó esta incidencia (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='locations.asistencia'),
        ),
        migrations.AlterUniqueTogether(
            name='incidencia',
            unique_together={('usuario', 'tipo', 'fecha')},
        ),
    ]
